-- AlterTable
ALTER TABLE "kitNotifStatus" ADD COLUMN     "d1" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "d2" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "d3" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "d4" BOOLEAN NOT NULL DEFAULT false;
