## https://ecozipo-codesource.onrender.com
# http://localhost:4000

# bfa3dc80b4e3d59749zxqg : Bureau
# bff96527f75046059crdcz : ancien
# bf97a670a088fa909f5ybe : nouveau compte principale maison youssouf (id 4)
# bfa8cbeabe840627eay2sh : secteur 02 maison youssouf (id 9)
# bfa6b3c635b2c0dd14q8hs : secteur 02 maison youssouf (id 11)
# bf5932770f24c12602nams : delete pour teste groupe (DID 5)


# bf0472e30a7dd94d38qxjy : kit koloina ( id(3) - compte(14) - kit(66) kit 9)
# bf16db50f054d26bf18p7f : Hybride pour koloina ( id(3) - compte(14) - kit(58) )
# bfb5228cb08652a25cpf9u : Hybride pour rianala ( id(3) - compte(14) - kit(67) ) // id rianala 4

# bfb235e344e6e436f9ejcy :  (4)


# bfbfdd93245b026a5arp3h 24 @ netsika (68)
# bf5932770f24c12602nams : (DID : 5)

# bf472b2ee2f03794aclmju : test brayan



### GET ALL KIT USER COMMUANUTE
GET https://ecozipo-codesource.onrender.com/getalluserforcommunaute




### GET COMMUNAUTE AVIS
POST  http://localhost:4000/getcommunauteavisbyuser
Content-Type: application/json
 
{
    "utilisateurId": "6"
}





### CREATE COMMUNAUTE AVIS
POST  https://ecozipo-codesource.onrender.com/createcommunauteavis
Content-Type: application/json
 
{
    "utilisateurId": "6"
}



### UPDATE COMMUNAUTE AVIS
POST  http://localhost:4000/updatecommunauteavis
Content-Type: application/json
 
{
    "utilisateurId": "6",
    "statistique": "3",
    "avis":""
}