# https://ecozipo-codesource.onrender.com
# http://localhost:4000

# bfa3dc80b4e3d59749zxqg : Bureau
# bff96527f75046059crdcz : maison

### get valeurbut KitValeurBut
POST https://ecozipo-codesource.onrender.com/getkitvaleurbyidkittongou
Content-Type: application/json

{
    "idKitTongou": "bff96527f75046059crdcz"
}


### Update KitValeurBut
POST https://ecozipo-codesource.onrender.com/updatekitvaleurbut
Content-Type: application/json

{
    "idKitTongou": "bfa3dc80b4e3d59749zxqg"
}



################################### NOTIFICATION ############################
POST https://ecozipo-codesource.onrender.com/getnotificationuserfiltre
Content-Type: application/json

{
    "utilisateurId": "6",
    "type":"IA"
}




